name: Linux Demo
on:
  push
jobs:
  success-case:
    runs-on: ubuntu-latest
    name: Successful case
    steps:
    - uses: actions/checkout@v2
    - name: build testapp
      run: |
        cd testapp
        gcc -o testapp -O0 -g testapp.c
        cd ..
    - name: run
      run: testapp/testapp -t 5
