name: Windows Demo
on:
  push
jobs:
  success-case:
    runs-on: windows-latest
    name: Successful case
    steps:
    - uses: actions/checkout@master
    - name: build testapp
      run: |
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        cd testapp
        cl.exe /nologo /Od /Zi testapp.c
        cd ..
      shell: cmd
    - name: run
        testapp\testapp.exe -t 5

